version: "3.9"

services:
  frontend:
    container_name: tp-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
      target: dev
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    restart: always
    depends_on:
      - backend

  backend:
    container_name: tp-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 4000:4000