version: "3.9"

services:
  frontend:
    container_name: tp-frontend
    image: tp-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    restart: always
    depends_on:
      - backend
  backend:
    container_name: tp-backend
    image: tp-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 4000:4000